version: "3.9"
services:
    frontend:
        build:
            context: ./react-frontend-starter/
        image: fullstack-react-fastapi-propel-frontend
        volumes:
          
          - ./react-frontend-starter/src:/usr/src/app # Mounts the local frontend folder into the container
          
        env_file:
          - ./react-frontend-starter/.env
        ports:
            - 3000:3000 

    backend:
        build:
            context: ./fastapi-backend-starter/
            network: host
        image: fullstack-react-fastapi-propel-backend
        volumes:
          - ./fastapi-backend-starter:/usr/src/app # Mounts the local backend folder into the container
        env_file:
          - ./fastapi-backend-starter/.env
        ports:
            - 3001:3001