version: "3.9"
services:
    frontend:
        build:
            context: ./react-frontend-starter/
        # command: npm run dev:watch
        image: fullstack-react-fastapi-propel-frontend
        volumes:
            - ./react-frontend-starter:/src/ # Mounts the local frontend folder into the container
            - nodemodules:/src/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true

        env_file:
            - ./react-frontend-starter/.env
        ports:
            - 3000:443

    backend:
        build:
            context: ./fastapi-backend-starter/
            network: host
        image: fullstack-react-fastapi-propel-backend
        volumes:
            - ./fastapi-backend-starter:/usr/src/app # Mounts the local backend folder into the container
        env_file:
            - ./fastapi-backend-starter/.env
        ports:
            - 3001:443
volumes:
    nodemodules: {}
