apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: service.beta.kubernetes.io/azure-dns-label-name"="health-monitor.westeurope.cloudapp.azure.com"
  namespace: app
  name: app-ingress
spec:
  rules:
  - host: health-monitor.westeurope.cloudapp.azure.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-container-service
            port:
              number: 80
