# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend
#   namespace: app
#   annotations:
#     kubernetes.io/ingress.class: azure-application-gateway
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: azure-application-gateway
#   rules:
#   - host: health-monitor.westeurope.cloudapp.azure.com
#     http:
#       paths:
#       - path: /app
#         backend:
#           service:
#             name: frontend-container-service
#             port:
#               number: 80
#         pathType: Exact



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontent-agic
  namespace: app
  annotations:
    kubernetes.io/ingress.class: azure-application-gateway
spec:
  rules:
  - host: health-data.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /app
        backend:
          service:
            name: frontend-container-service
            port:
              number: 80
        pathType: Exact
