apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: app
  name: app-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app
        backend:
          serviceName: frontend-container-service
          servicePort: 80
