apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: app
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: frontend-container-service
            port:
              number: 80
        pathType: Exact
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#   namespace: app
#   name: app-ingress
# spec:
#   rules:
#   - host: health-monitor.westeurope.cloudapp.azure.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: frontend-container-service
#             port:
#               number: 80



# helm upgrade --install ingress-nginx ingress-nginx \
#  --repo https://kubernetes.github.io/ingress-nginx \
#  --namespace app \
#  --create-namespace \
#  --set rbac.create=true \
#  --set controller.stats.enabled=true \
#  --set controller.metrics.enabled=true \
#  --set controller.service.externalTrafficPolicy="Local" \
#  --set controller.service.loadBalancerIP="20.16.118.226" \
#  --set controller.service.annotations."service.beta.kubernetes.io/azure-dns-label-name"="health-monitor.westeurope.cloudapp.azure.com"


# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm repo update
# helm install ingress-nginx ingress-nginx/ingress-nginx \
#     --namespace app \
#     --set controller.replicaCount=2 \
#     --set controller.nodeSelector."kubernetes\.io/os"=linux \
#     --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"="rg-fast-react-dev-weu" \
#     --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
#     --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="health-data.westeurope.cloudapp.azure.com" \
#     --set controller.service.loadBalancerIP="20.160.205.34"
