apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - name: backend-container
    image: acr.io/app/backend:latest
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
  - name: frontend-container
    image: acr.io/app/frontend:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
