name: deploy-infra
run-name: ${{ github.workflow }}
on:
    push:
        branches:
            - master
        paths:
            - "bicep/**"
            - ".github/workflows/deploy.yml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

env:
    BICEP_DIR: bicep
jobs:
    deploy-infrastructure:
        name: deploy-infrastructure
        runs-on: ubuntu-latest
        #environment: production-infrastructure
        permissions:
            contents: read
        defaults:
            run:
                shell: bash
                working-directory: ${{ env.BICEP_DIR }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure login
              uses: Azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Lint template
              run: az bicep build --file azure.deploy.bicep

            - name: Validate template
              run: |
                  az deployment sub validate \
                  --name "${{ vars.DEPLOYMENT_NAME }}" \
                  --location "${{ vars.LOCATION }}" \
                  --template-file azure.deploy.bicep \
                  --parameters azure.deploy.parameters.json

            - name: Deploy template
              run: |
                  az stack sub create \
                  --name "${{ vars.DEPLOYMENT_NAME }}" \
                  --location "${{ vars.LOCATION }}"  \
                  --template-file azure.deploy.bicep \
                  --parameters azure.deploy.parameters.json \
                  --deny-settings-mode None
